### ISSUE TITLE
java1.8报错

### ISSUE THREAD

**Issue by brodbus** [KnIfER/mdict-java#2]
../com/knziha/plod/dictionary/mdict.java:374: 错误: 找不到符号
        int blockId = accumulation_blockId_tree.xxing(new myCpr(position,1)).getKey().value;
                                                                                     ^
  符号:   变量 value
  位置: 接口 Comparable
../com/knziha/plod/dictionary/mdict.java:383: 错误: 找不到符号
        int Rinfo_id = accumulation_RecordB_tree.xxing(new myCpr(infoI.key_offsets[i],1)).getKey().value;
                                                                                                  ^
  符号:   变量 value
  位置: 接口 Comparable
../com/knziha/plod/dictionary/mdict.java:941: 错误: 找不到符号
	    		int RecB_ID = accumulation_RecordB_tree.xxing(new myCpr(infoI.key_offsets[position],1)).getKey().value;
	    		                                                                                                ^
  符号:   变量 value
  位置: 接口 Comparable
../com/knziha/plod/dictionary/mdict.java:1172: 错误: 找不到符号
        int blockId = accumulation_blockId_tree.xxing(new myCpr(position,1)).getKey().value;
                                                                                     ^
  符号:   变量 value
  位置: 接口 Comparable
注: ../com/knziha/plod/dictionary/mdict.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
4 个错误
我在MAC下尝试运行报错，这个怎么解决？

**Comment by KnIfER** [comment]
myCpr 之后加 <> 试试。。

**Comment by KnIfER** [comment]
然后可能需要类型转换什么的。

**Comment by freboat** [comment]
踩到同样的坑了，　　能贴句完成代码吗，　java小白把<integer,integer>换了好几个地方　
编译还是报错

**Comment by freboat** [comment]
搞定了原来只要　mycpr<>(new ...)
