### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException issue

### ISSUE THREAD

**Issue by imchlorine** [KnIfER/mdict-java#5]
Hi,
I got an issue when I run the fuzzy search in MDTest.java
![image](https://user-images.githubusercontent.com/16852792/61046782-4f21c500-a421-11e9-9108-2429e4bc6de2.png)

![image](https://user-images.githubusercontent.com/16852792/61046163-c9514a00-a41f-11e9-82cb-6393237772ff.png)

It seems the problem is in flowerFindAllKeys(). I've tried to debug, but not be able to fix it.

**Comment by MartinRakacolli** [comment]
I can try taking a look at it.

**Comment by KnIfER** [comment]
what's your dictionary, and can I have a copy of it?

**Comment by imchlorine** [comment]
Sure. I've uploaded to Google Drive [Dictionary](https://drive.google.com/file/d/1k6n9237QiKvXiUKlJWeaXr5dSTW6MiLy/view?usp=sharing)

**Comment by KnIfER** [comment]
访问不了……

**Comment by imchlorine** [comment]
好的
[Cobuild5.mdx.zip](https://github.com/KnIfER/mdict-java/files/3411413/Cobuild5.mdx.zip)

**Comment by KnIfER** [comment]
the common cache for index blocks `final byte[] key_block = new byte[65536];` is too small in this case.

uncomment the CMN.show and you can see the needed size `infoI.key_block_decompressed_size` is actually **102399**

should be fixed now.
